package:
  name: ccpi-reconstruction
  version: {{ environ['CIL_VERSION'] }}


build:
  preserve_egg_dir: False
  script_env:
    - CIL_VERSION   
#  number: 0
  
requirements:
  build:
    - python
    - numpy x.x
    - setuptools
    - boost >=1.64
    - boost-cpp >=1.64
    - cython
    - libtiff
    - cil_reconstruction =={{ environ['CIL_VERSION'] }}
    - cmake >=3.1

  run:
    - python
    - numpy x.x
    - boost >=1.64
    - libtiff
    - h5py
    - scipy
    - cil_reconstruction =={{ environ['CIL_VERSION'] }}

	
about:
  home: http://www.ccpi.ac.uk
  license:  Apache 2.0 License
  summary: 'CCPi Iterative Reconstructor - CGLS, MLEM, SIRT with TV'
