function [ nvoxels niterations beam_harden ok ] = input_recon_data( )
%input_recon_data
%   GUI function to get user settings for 
%      - number of voxels (cubed)
%      - number of iterations
%      - whether to use beam hardening
%      - whether user accepted values or cancelled

ok = false;
nvoxels = 250;
niterations = 10;
beam_harden = true;

H = figure('Units', 'Normalized',...
           'Position', [0.1 0.1 0.5 0.5],...
           'Toolbar', 'None',...
           'Name', 'Input data for cgls reconstruction',...
           'WindowStyle', 'Modal');
       
okgui = uicontrol('Parent', H,...
                  'Units', 'Normalized',...
                  'Position', [0.2 0.1 0.2 0.1],...
                  'Style', 'pushbutton',...
                  'String', 'OK',...
                  'Callback', @okfn );
              
cancelgui = uicontrol('Parent', H,...
                      'Units', 'Normalized',...
                      'Position', [0.6 0.1 0.2 0.1],...
                      'Style', 'pushbutton',...
                      'String', 'Cancel',...
                      'Callback', @cancelfn );

voxgui = uicontrol('Parent', H,...
                   'Units', 'Normalized',...
                   'Position', [0.5 0.9 0.4 0.05],...
                   'Style', 'edit',...
                   'String', num2str(nvoxels),...
                   'Callback', @voxfn );
              
itergui = uicontrol('Parent', H,...
                    'Units', 'Normalized',...
                    'Position', [0.5 0.75 0.4 0.05],...
                    'Style', 'edit',...
                    'String', num2str(niterations),...
                    'Callback', @iterfn );
              
beamgui = uicontrol('Parent', H,...
                    'Units', 'Normalized',...
                    'Position', [0.5 0.6 0.1 0.05],...
                    'Style', 'checkbox',...
                    'Value', beam_harden,...
                    'Callback', @beamfn );
          
voxlabel = uicontrol('Parent', H,...
                    'Units', 'Normalized',...
                    'Position', [0.1 0.9 0.4 0.05],...
                    'Style', 'text',...
                    'String', 'Number of Voxels');

iterlabel = uicontrol('Parent', H,...
                      'Units', 'Normalized',...
                      'Position', [0.1 0.75 0.4 0.05],...
                      'Style', 'text',...
                      'String', 'Number of iterations');
              
beamlabel = uicontrol('Parent', H,...
                      'Units', 'Normalized',...
                      'Position', [0.1 0.6 0.4 0.05],...
                      'Style', 'text',...
                      'String', 'Use beam hardening');

uiwait(H);
               
    function okfn(cbo, eventdata)
        % callback for OK button
        ok = true;
        uiresume;
        delete(H);
    end

    function cancelfn(cbo, eventdata)
        % callback for Cancel button
        ok = false;
        uiresume;
        delete(H);
    end

    function voxfn(cbo, eventdata)
        % callback for number of voxels
        val = get(cbo, 'String');
        nvoxels = str2num(val);
    end

    function iterfn(cbo, eventdata)
        % callback for number of iterations
        val = get(cbo, 'String');
        niterations = str2num(val);
    end

    function beamfn(cbo, eventdata)
        % callback for use of beam hardening
        beam_harden = not(beam_harden);
    end

end

